import { describe, it, expect } from 'vitest';
import { parseLockfile, parseLockfileWithGraph, findLockfile } from '../src/core/lockfile.js';
import { resolve, dirname } from 'node:path';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';

function withLockfile(
  filename: string,
  content: string,
  run: (lockfilePath: string) => void,
): void {
  const dir = mkdtempSync(resolve(tmpdir(), 'vuln-symtrace-ts-lock-'));
  try {
    const lockfilePath = resolve(dir, filename);
    writeFileSync(lockfilePath, content);
    run(lockfilePath);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function withYarnProject(
  yarnLock: string,
  packageJson: object,
  run: (lockfilePath: string) => void,
): void {
  const dir = mkdtempSync(resolve(tmpdir(), 'vuln-symtrace-ts-yarn-'));
  try {
    const lockfilePath = resolve(dir, 'yarn.lock');
    writeFileSync(lockfilePath, yarnLock);
    writeFileSync(resolve(dir, 'package.json'), JSON.stringify(packageJson));
    run(lockfilePath);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const PNPM_SAMPLE = `lockfileVersion: '9.0'

importers:

  .:
    dependencies:
      lodash:
        specifier: 4.17.20
        version: 4.17.20
    devDependencies:
      '@scope/tool':
        specifier: 1.0.0
        version: 1.0.0(react@18.2.0)

packages:

  lodash@4.17.20:
    resolution: {integrity: sha512-aaa}

  '@scope/tool@1.0.0':
    resolution: {integrity: sha512-bbb}

  transitive-dep@2.3.4:
    resolution: {integrity: sha512-ccc}

snapshots:

  lodash@4.17.20: {}

  '@scope/tool@1.0.0(react@18.2.0)':
    dependencies:
      transitive-dep: 2.3.4

  transitive-dep@2.3.4: {}
`;

const NPM_SAMPLE = JSON.stringify({
  name: 'fixture',
  lockfileVersion: 3,
  packages: {
    '': {
      name: 'fixture',
      dependencies: { lodash: '^4.17.0' },
      devDependencies: { semver: '^5.0.0' },
    },
    'node_modules/lodash': { version: '4.17.20' },
    'node_modules/semver': { version: '5.7.1' },
    'node_modules/minimist': { version: '0.0.8' },
    'node_modules/@scope/bar': { version: '2.0.0' },
    'node_modules/mkdirp/node_modules/foo': { version: '1.0.0' },
  },
});

const YARN_SAMPLE = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.0, lodash@^4.17.20:
  version "4.17.20"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.20.tgz#hash"
  integrity sha512-aaa

"@scope/tool@^1.0.0":
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/@scope/tool/-/tool-1.0.0.tgz#hash"
  integrity sha512-bbb

minimist@0.0.8:
  version "0.0.8"
  resolved "https://registry.yarnpkg.com/minimist/-/minimist-0.0.8.tgz#hash"
  integrity sha512-ccc
`;

const YARN_PKG = {
  name: 'fixture',
  dependencies: { lodash: '^4.17.0' },
  devDependencies: { '@scope/tool': '^1.0.0' },
};

const BERRY_SAMPLE = `__metadata:
  version: 8
  cacheKey: 10

"lodash@npm:^4.17.0":
  version: 4.17.20
  resolution: "lodash@npm:4.17.20"
`;

// express -> cookie, plus a nested copy of `shared` that must win over the
// hoisted one when resolving `a`'s dependency.
const NPM_GRAPH_SAMPLE = JSON.stringify({
  name: 'fixture',
  lockfileVersion: 3,
  packages: {
    '': { name: 'fixture', dependencies: { express: '^4.0.0', a: '^1.0.0' } },
    'node_modules/express': {
      version: '4.18.0',
      dependencies: { cookie: '^0.5.0' },
    },
    'node_modules/cookie': { version: '0.5.0' },
    'node_modules/a': { version: '1.0.0', dependencies: { shared: '^1.0.0' } },
    'node_modules/a/node_modules/shared': { version: '1.5.0' },
    'node_modules/shared': { version: '2.0.0' },
  },
});

const YARN_GRAPH_SAMPLE = `# yarn lockfile v1

express@^4.0.0:
  version "4.18.0"
  dependencies:
    cookie "^0.5.0"

cookie@^0.5.0:
  version "0.5.0"
`;

const YARN_GRAPH_PKG = {
  name: 'fixture',
  dependencies: { express: '^4.0.0' },
};

describe('parseLockfile (pnpm)', () => {
  it('flags packages declared in importers as direct', () => {
    withLockfile('pnpm-lock.yaml', PNPM_SAMPLE, (lockfilePath) => {
      const packages = parseLockfile(lockfilePath);
      const byName = new Map(packages.map((pkg) => [pkg.name, pkg]));

      expect(packages).toHaveLength(3);
      expect(byName.get('lodash')).toEqual({
        name: 'lodash',
        version: '4.17.20',
        isDirect: true,
      });
    });
  });

  it('splits scoped package keys and strips peer suffixes', () => {
    withLockfile('pnpm-lock.yaml', PNPM_SAMPLE, (lockfilePath) => {
      const scoped = parseLockfile(lockfilePath).find(
        (pkg) => pkg.name === '@scope/tool',
      );

      expect(scoped).toEqual({
        name: '@scope/tool',
        version: '1.0.0',
        isDirect: true,
      });
    });
  });

  it('flags packages absent from importers as transitive', () => {
    withLockfile('pnpm-lock.yaml', PNPM_SAMPLE, (lockfilePath) => {
      const transitive = parseLockfile(lockfilePath).find(
        (pkg) => pkg.name === 'transitive-dep',
      );

      expect(transitive?.isDirect).toBe(false);
    });
  });
});

describe('parseLockfileWithGraph (pnpm)', () => {
  it('builds the dependency graph from the snapshots section', () => {
    withLockfile('pnpm-lock.yaml', PNPM_SAMPLE, (lockfilePath) => {
      const { graph } = parseLockfileWithGraph(lockfilePath);

      // Snapshot keys carry a peer suffix that must be stripped.
      expect(graph.get('@scope/tool@1.0.0')).toEqual(['transitive-dep@2.3.4']);
      expect(graph.get('lodash@4.17.20')).toEqual([]);
    });
  });

  it('still returns the installed package list alongside the graph', () => {
    withLockfile('pnpm-lock.yaml', PNPM_SAMPLE, (lockfilePath) => {
      const { packages } = parseLockfileWithGraph(lockfilePath);
      expect(packages).toHaveLength(3);
    });
  });
});

describe('parseLockfileWithGraph (npm)', () => {
  it('builds the dependency graph from the packages section', () => {
    withLockfile('package-lock.json', NPM_GRAPH_SAMPLE, (lockfilePath) => {
      const { graph } = parseLockfileWithGraph(lockfilePath);
      expect(graph.get('express@4.18.0')).toEqual(['cookie@0.5.0']);
    });
  });

  it('resolves a dependency to the nearest node_modules copy', () => {
    withLockfile('package-lock.json', NPM_GRAPH_SAMPLE, (lockfilePath) => {
      const { graph } = parseLockfileWithGraph(lockfilePath);
      // `a` must resolve `shared` to its nested 1.5.0, not the hoisted 2.0.0.
      expect(graph.get('a@1.0.0')).toEqual(['shared@1.5.0']);
    });
  });
});

describe('parseLockfileWithGraph (yarn classic)', () => {
  it('builds the dependency graph from resolved entries', () => {
    withYarnProject(YARN_GRAPH_SAMPLE, YARN_GRAPH_PKG, (lockfilePath) => {
      const { graph } = parseLockfileWithGraph(lockfilePath);
      expect(graph.get('express@4.18.0')).toEqual(['cookie@0.5.0']);
    });
  });
});

describe('parseLockfile (npm)', () => {
  it('flags packages from the root entry as direct, others as transitive', () => {
    withLockfile('package-lock.json', NPM_SAMPLE, (lockfilePath) => {
      const byName = new Map(
        parseLockfile(lockfilePath).map((pkg) => [pkg.name, pkg]),
      );

      expect(byName.get('lodash')).toEqual({
        name: 'lodash',
        version: '4.17.20',
        isDirect: true,
      });
      expect(byName.get('semver')?.isDirect).toBe(true);
      expect(byName.get('minimist')?.isDirect).toBe(false);
    });
  });

  it('extracts the package name from nested and scoped node_modules paths', () => {
    withLockfile('package-lock.json', NPM_SAMPLE, (lockfilePath) => {
      const packages = parseLockfile(lockfilePath);

      expect(packages.find((pkg) => pkg.name === 'foo')).toEqual({
        name: 'foo',
        version: '1.0.0',
        isDirect: false,
      });
      expect(packages.find((pkg) => pkg.name === '@scope/bar')?.version).toBe(
        '2.0.0',
      );
    });
  });
});

describe('parseLockfile (yarn classic)', () => {
  it('flags packages from package.json as direct, others as transitive', () => {
    withYarnProject(YARN_SAMPLE, YARN_PKG, (lockfilePath) => {
      const byName = new Map(
        parseLockfile(lockfilePath).map((pkg) => [pkg.name, pkg]),
      );

      expect(byName.get('lodash')).toEqual({
        name: 'lodash',
        version: '4.17.20',
        isDirect: true,
      });
      expect(byName.get('@scope/tool')?.isDirect).toBe(true);
      expect(byName.get('minimist')?.isDirect).toBe(false);
    });
  });

  it('handles multi-spec headers and scoped names', () => {
    withYarnProject(YARN_SAMPLE, YARN_PKG, (lockfilePath) => {
      const packages = parseLockfile(lockfilePath);

      expect(packages).toHaveLength(3);
      expect(packages.find((pkg) => pkg.name === '@scope/tool')?.version).toBe(
        '1.0.0',
      );
    });
  });

  it('rejects yarn berry (v2+) lockfiles with a clear error', () => {
    withYarnProject(BERRY_SAMPLE, YARN_PKG, (lockfilePath) => {
      expect(() => parseLockfile(lockfilePath)).toThrow(/Berry/);
    });
  });
});

describe('parseLockfile (errors)', () => {
  it('throws for unsupported lockfile names', () => {
    expect(() => parseLockfile('/tmp/bun.lockb')).toThrow(
      /Unsupported lockfile/,
    );
  });
});

describe('findLockfile', () => {
  it('finds a pnpm-lock.yaml in a directory', () => {
    withLockfile('pnpm-lock.yaml', PNPM_SAMPLE, (lockfilePath) => {
      expect(findLockfile(dirname(lockfilePath))).toBe(lockfilePath);
    });
  });

  it('finds a package-lock.json in a directory', () => {
    withLockfile('package-lock.json', NPM_SAMPLE, (lockfilePath) => {
      expect(findLockfile(dirname(lockfilePath))).toBe(lockfilePath);
    });
  });

  it('finds a yarn.lock in a directory', () => {
    withYarnProject(YARN_SAMPLE, YARN_PKG, (lockfilePath) => {
      expect(findLockfile(dirname(lockfilePath))).toBe(lockfilePath);
    });
  });

  it('throws when no supported lockfile exists', () => {
    const dir = mkdtempSync(resolve(tmpdir(), 'vuln-symtrace-ts-empty-'));
    try {
      expect(() => findLockfile(dir)).toThrow(/No supported lockfile/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
